name: PermissionPurge
version: '1.0.1'
main: dev.ev1dent.permissionpurge.PPMain
api-version: '1.20'
depend: [ LuckPerms ]
commands:
  pp:
    usage: /<command> [user|group] <user|group> <permission>
    aliases:
      - purgeperms
      - purge
      - purgepermissions
    description: "Purge all permissions LuckPerms User / Group"
    permission: permissionpurge.purge