name: PermissionPurge
version: '1.0.2'
main: dev.ev1dent.permissionpurge.PPMain
api-version: '1.20'
depend: [ LuckPerms ]
commands:
  pp:
    usage: /<command> [user|group] <user|group> <permission>
    aliases:
      - purgeperms
      - purge
      - purgepermissions
      - permissionpurge
    description: "Purge all matched permissions from a LuckPerms user or group."
    permission: permissionpurge.purge